---
- name: update yum repository
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: install epel-release
  yum:
    name: 'epel-release'
    state: latest

- name: install git, docker and python-docker-py
  yum:
    name: "{{ item }}"
  with_items:
    - git
    - docker
    - python-docker-py

- name: start docker
  notify:
    - start-docker
