---
- name: yum update
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: install epel-release
  yum:
    name: 'epel-release'
    state: latest

- name: install items with yum
  yum:
    name: "{{ item }}"
  with_items:
    - git
    - docker
    - python-docker-py

# - name: start docker
#   systemd:
#     name: docker
#     state: started
#
# - name: enable docker
#   systemd:
#     name: docker
#     enabled: yes
#
# - name: git clone awx
#   git:
#     repo: 'https://github.com/ansible/awx.git'
#     dest: /opt/
#     clone: yes
#
# - name: install awx
#   shell: cd "/opt/installer" && /bin/ansible-playbook -i inventory install.yml
