---
 - name: Install dependencies
   yum:
     name: "{{ item }}"
   with_items:
     - docker
     - git
     - python-docker-py
     - ansible

 - name: start docker
   notify:
     - start-docker

 - name: git clone awx
   git:
     repo: 'https://github.com/ansible/awx.git'
     dest: /opt/awx/
     clone: yes

 - name: install awx
   shell: cd "/opt/awx/installer" && /bin/ansible-playbook -i inventory install.yml
