---
 - name: Install dependencies
   yum:
     name: "{{ item }}"
   with_items:
     - docker
     - git
     - python-docker-py
   notify:
   - start docker
   - enable docker

 - name: create temporary build directory
   tempfile:
     state: directory
     suffix: build
   register: tmpdir

 - name: git clone awx
   git:
     repo: 'https://github.com/ansible/awx.git'
     dest: /opt/awx/
     clone: yes

 - name: install awx
   shell: cd "/opt/installer" && /bin/ansible-playbook -i inventory install.yml
